### ISSUE TITLE
.button-container__link:visited   (redundant)?

### ISSUE THREAD

**Issue by SavageWilliam** [FAC9/future-leaders#69]
In footer.css
The selector: 'button-container__link:visited' (line:11) I believe is redundant? removing it I cant see any change in styling after interaction.

I could be wrong in which case I'd love to be educated on this one 👍

**Comment by njsfield** [comment]
Thank you for spotting :)

**Comment by jsms90** [comment]
![image](https://cloud.githubusercontent.com/assets/15656538/21392134/6854f51c-c786-11e6-9223-eba2e0e134f9.png)

Without this, if you click on the donate button and then press back, the word donate has the classic blue colour

**Comment by jsms90** [comment]
@SavageWilliam Is it ok to close this issue?

**Comment by SavageWilliam** [comment]
@jsms90  sure do it. So this is an alternative to an attribute text-decoration:none?
